### ISSUE TITLE
Create/improve the general design of the site

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#1]
Define a layout for the home page that will be use for most page. Navbar and etc, will be define in this template.

**Comment by marcandregirard** [comment]
I'm updating this issue so that we can discuss, share idea about what the site could look like. This include colors, ui improvement, things that get on your nerves at the moment anything.

**Comment by olamarche** [comment]
The navbar has been updated

**Comment by marcandregirard** [comment]
Close since this is now on the frond-end side of the application
