### ISSUE TITLE
Fix one to many

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#10]
For an unknown reason, the one to many relation between MapPoint and Entity does not work.

**Comment by mrheaumeproulx** [comment]
I think it might be your name that aren't right in your relationship:
Entity Model:
belongs_to :map_point

map_point model:
has_many: entitys

(not sure if rails follows the grammar rules when it comes to model names)

**Comment by marcandregirard** [comment]
I need to check that again, but even if I use the right pluralize/not pluralize form, I did not work. I need to create the test to check the relation. (I need to add a lot of tests in fact.)

**Comment by marcandregirard** [comment]
Looks like I did not test it properly when I changed the `belongs_to :map_points` to `belongs_to :map_point`. It's working fine now.
