### ISSUE TITLE
Share the documents about the project

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#12]
We should create the external folder to share the documentation about the project (list of features, layout and etc). It could be any of the following share services (DropBox, ShareDrive, Google Drive etc.).

We could have a board with features to develop. I know Waffle IO with GitHub Issue, but there are others alternatives ( Pivotal Tracker, JIRA etc)

**Comment by mrheaumeproulx** [comment]
I'll put the documents in google drive, we already had a folder named Projects and inside I made a folder names RailsGame. Tell me he see those folders, because this is where I'll put the documents.

**Comment by marcandregirard** [comment]
It's fine with me !

**Comment by mrheaumeproulx** [comment]
Documents are on Google Drive
