### ISSUE TITLE
Issue with sign in from facebook

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#13]
When I try to log in from Facebook, I got the following error message : 

App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

This is not too useful at the moment, since I can't test the sign in option.

**Comment by mrheaumeproulx** [comment]
I want to add a you as an administrator of the Facebook app but you'll need to confirm your account or you won't be able to connect to it

Here is the link explaining the procedure (really simple, annoying but simple): https://www.facebook.com/help/verify

**Comment by marcandregirard** [comment]
Done :D
