### ISSUE TITLE
User with multiple sign-in option

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#18]
We should be able to have multiple sign-in option for the same account.

**Comment by mrheaumeproulx** [comment]
If I understand correctly
- A user connects with Facebook and creates a player, but if he wishes to connect with gmail, he should be able to do so and retrieve the same player

**Comment by marcandregirard** [comment]
Exactly! You should be able to have multiple sign in method and be able to connect to the same account with different providers. You need to be sign in to add/remove authenfication.
