### ISSUE TITLE
Map Tiles terrain

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#28]
Create terrain class for map tiles. Assign a colour for each terrain. We leave it at that for the moment.

**Comment by marcandregirard** [comment]
@LepageT  Would you want to work on this ? I think you're working on the tutorial at the moment, it could be an easy task to start in the project.

**Comment by LepageT** [comment]
Sure no problem. I will take a look.

**Comment by marcandregirard** [comment]
You can chat with us on : https://gitter.im/banane-io/PDB if you want more info or you have some question.
