### ISSUE TITLE
Do we need more treble ? No drop the BASS!

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#38]
Let's have a first try at creating a base for the player. First, we need to let the player to decide where the base will be located (that means the base should not be the first thing the player can do)., so we don't have to limit the player on location (unless he wants a base on water that's dumb dumb). The creation of the base will need resources to build it. You would start with only only one building that would enable to do some new actions (produce resources/ train soldiers). The player could gather more resources to create new buildings: A first list of buildings we could have : garden(food), fields, dorms, house for peasants, forge/blacksmith, windmill and etc.

Do we limit the number of slots of buildings we can build on a base or do we make the buildings level-able, I don't a clue! We could have a way to simulate reality by having a way to deteriorate building over-time. You would need to repair or destroy and recreate buildings to keep production up.
- [ ] Create the action of building the base
- [ ] Create the concept of buildings
- [ ] Create the concept of reparation
- [ ] Create a view for the base

At one point, we could make the base cooler by making the base shareable. Imagine we have quests and you need to travel a lot, who will maintain orders and repair buildings? Why not your friends or clan members? 

We could let people conquer or raid people's base in a pvp server, but for the moment let's create something simple.

**Comment by mrheaumeproulx** [comment]
What is the first base of the player?

Right now we are centered around a hero that will create a base on one tile of the map. But when we start, is the player actually going to start right away to gather resources, or should he make a base first and be able to gather resources only when in it?

I thought that the hero could have a camp item in his inventory (right now there is isn't we just assume that he has one). Create a camp on the map. The camp his is base but, when like the first stage. Once the camp is setup and the player is in it, he can gather resource by doing actions available through the base, for example: Go Lumbering. Once he has enough resource, he can build a Lumberjack that starts gathering wood automatically.

So yeah here are all the questions I have:


These are thoughts.For now I'll implement the base creation and the building concept as well.

**Comment by marcandregirard** [comment]
I sort of imagined it that way, creating a small camp and then growing from there. Doing collections of resources from the base is a good idea! The thing with starting with a small camp is it does not feels like it's permanent. I have the feeling that players will want to delete their base and explore more before choosing a base permanently.  So go with what you feel right on this one. I would start with implementing a small base class and one or two buildings, then from there I would experiments. 

The resources available should be based on what ? Do you need to be near mountains to  have stone ? How will we deal with this ? People need waters, do we need to setup near waters or do we consider every map point have waters ? 

You'll have to decide if you can move in your base (like having a small map to move around your base (we could leave this for a v2 of the base)

**Comment by mrheaumeproulx** [comment]
I think we should use another term than camp. The problem camp is strongly implies that it could be movable. The camp should then be used for something else. Be maybe we say something like Establish a village here. Village being less movable will not really give the player the urge to move it somewhere else.

Resources available should be base on the terrain the base is established. (Player could "Inspect" the terrain to see the resources available, some titles could have higher modifiers even though it is the same terrain and that raises more questions). For the moment, I think wood, should be the first resources that the village uses and as it progresses, wood might become deprecated and replaced for stone.

Degradation of buildings over time might be a little too much. I really hate the concept in a game. I think it isn't really fun for the player to keep their buildings in perfect conditions. If the player has 5 bases with many buildings, maintaining them would be a pain and the ass. I see this feature as a way to slow down player progress as well. I might be against Degradation over time, but I like the idea of degradation of buildings by attacks from another player for example.

For water, it might be me, but want if we lets just say People have a way to get their water(no water managing) or we create wells(building related) without need to be close to water.

**Comment by marcandregirard** [comment]
We don't need to have the concept of water at all, I was just raising a question for realism ( I don't really think we need to take this into account). 

I see that the degradation of building is maybe not something we want. We should put this on the ice, and see later if we need something to slow down the player. The thing I hope to achieve in the game is the player always have something to do in the game, so if you can always play we will need a system to slowdown players that are too active versus people that just play 15 minutes to not create gaps and the need to be permanently online.

**Comment by mrheaumeproulx** [comment]
I see your point, but degradation affects both type of players, both will progress slower. So I agree with you we will need a system that slows down fast players but doesn't penalize the slower players.

**Comment by marcandregirard** [comment]
Degradation would have been base on use and not over-time. The formula i was thinking would have been something like degradation = numberOfUse x amount and not degradation = time x amount.

So anyway let's keep things simple and maybe leave reparation if we make base attackable in a pvp server or maybe with event like npc faction attacking your city village.

**Comment by marcandregirard** [comment]
The initial creation of the base is done. I'll create issue in the clubhouse project to continue iterating the idea.
