### ISSUE TITLE
Edge of the grid

### ISSUE THREAD

**Issue by LepageT** [banane-io/PDB#40]
When reaching the bottom or the right of the grid, the grid shrink. Ex: if we're at the far right we only have a 1 x 10 grid and if we're a the bottom right corner, only a 1 x 1 grid.

**Comment by marcandregirard** [comment]
Reproduced on develop. I thought I had this fixed, I'll need to check my code.

**Comment by marcandregirard** [comment]
Fixed and redeployed on Heroku.
