### ISSUE TITLE
Player id in url

### ISSUE THREAD

**Issue by LepageT** [banane-io/PDB#41]
The id of the player should not be in the URL. Ex: localhost:3000/players/1/edit

**Comment by marcandregirard** [comment]
We still need an identifier in the url to show the resources. Is this really a bug ? What do you find buggy about showing the id of the player ?

**Comment by olamarche** [comment]
You could use Friendly_id gems if you dont like the id in the URL.
https://github.com/norman/friendly_id

or you can change your route URL to : localhost:3000/players/username/edit

**Comment by LepageT** [comment]
I think it's a good idea to se the username instead of the id for the player.

**Comment by marcandregirard** [comment]
This is not a bug anymore in the java version since it's not implemented yet.
