### ISSUE TITLE
Access key of .env file

### ISSUE THREAD

**Issue by mrheaumeproulx** [banane-io/PDB#44]
My question is how to access the secret_keys in .env file. For example, in database.yml, you can access it via rails syntax <%= KEY %>. But now I need to access them in devise.rb, a ruby file.

I know Marc you made some changes in the application to make it work on Heroku. I'd like to know what is  the whole process to access a key in the actual application, like what is the gem used, when are they loaded etc. 

I have a general idea, but details would be helpful as I don't want to break the actual code when making my changes

**Comment by marcandregirard** [comment]
When you want to use a key from the .env file in a ruby file, just use ENV['KEY'] to get the value.

**Comment by mrheaumeproulx** [comment]
Ah! damn it I was missing the   '    ..... >.<
