### ISSUE TITLE
Add creation of account with mail and password

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#52]
The google and facebook signin are nice but we should be able to create a simple account.

**Comment by Mirv** [comment]
I'd be willing to help with this part - I did this last spring.  I'd say keep the other omniauth logins, but we just have it all for now.  I am not familar with cancancan myself, but I will peak that & see what it needs on the user table before I start.  Side note, ... we probably need a dashboard to manage all the games players are in eventually if its anything like that game you linked (https://en.wikipedia.org/wiki/OGame), where players can have multiple games active.

**Comment by Mirv** [comment]
Checklist

- [x] views extracted (already)
- [x] routes set for sessions (piggybacked current template)
- [x] enable sign in form on the default devise view
- [x] enable sign up route ensuring available
- [x] make link adjustments
- [x] controller up - using default in devise

Tests 

- [ ] tests no duplicate names 
- [ ] validations like user_id
- [ ] test creation redirects to record or success message
- [ ] test count of the db table affected for user / registration

**Comment by Mirv** [comment]
https://github.com/banane-io/PDB/pull/58

Pull request formed - per above did not duplicate devise tests.

Might want/need an integration test which does routing/db success checks.  Then model test of validations.  Not sure how to test user_id as unsure where this comes from.

**Comment by marcandregirard** [comment]
This is not relevant anymore since in the java version I have a username/password signup. I'll recreate an issue if I want to move to email/password or change something in the account creation.
