### ISSUE TITLE
Use of bcrypt or alternative for hasing pwd?

### ISSUE THREAD

**Issue by Mirv** [banane-io/PDB#55]
Just incase anything ever happens, it might be a decent idea to use bcrypt to ensure the passwords have that extra layer of protection (as some people use the same pwd for all games or all internet stuff...wise or not of them)?

**Comment by Mirv** [comment]
Nm,...looks like you're using the built in devise method for it?  Which might require bcrypt already?

**Comment by marcandregirard** [comment]
We need to check best practices but yes we need to protect the information of everyone :)

**Comment by marcandregirard** [comment]
Not relevant anymore in the Java app
