### ISSUE TITLE
Create an Heroku project

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#9]
We should have an Heroku instance that always run, where we could test more complicated scenario and have a "production" environment.

**Comment by marcandregirard** [comment]
The project is now up and running on Heroku. I'm having issue with the css and the signin. This will need more investiguation.

**Comment by marcandregirard** [comment]
Assets are not loading too.

**Comment by olamarche** [comment]
http://natashatherobot.com/rails-4-heroku-assets-not-found-css-image/

**Comment by marcandregirard** [comment]
I fix it. I needed to add the gem  'rails_12factor' since the integration between rails 4 and Heroku needed some work.

**Comment by marcandregirard** [comment]
Facebook auth is working on Heroku!
